        
        transfer = test->transferSize;
        char* ec_buffer = (char*)malloc(sizeof(char)*16*transfer);
        test->offset = offsetArray[0];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: single 512K: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[5];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, transfer, test);
        test->offset = offsetArray[10];
        IOR_Xfer(access, fd, ec_buffer, transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: two 512K: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[20];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 2*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: single 1MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[40];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 2*transfer, test);
        test->offset = offsetArray[60];
        IOR_Xfer(access, fd, ec_buffer, 2*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: two 1MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[100];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 4*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: single 2MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[140];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 4*transfer, test);
        test->offset = offsetArray[180];
        IOR_Xfer(access, fd, ec_buffer, 4*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: two 2MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[240];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 8*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: single 4MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[400];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 8*transfer, test);
        test->offset = offsetArray[560];
        IOR_Xfer(access, fd, ec_buffer, 8*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: two 4MB: %lf\n", xfer_endTime - xfer_startTime);
        test->offset = offsetArray[700];
        xfer_startTime = GetTimeStamp() - startTime;
        IOR_Xfer(access, fd, ec_buffer, 16*transfer, test);
        xfer_endTime = GetTimeStamp() - startTime;
        fprintf(stdout, "##request test: single 8MB: %lf\n", xfer_endTime - xfer_startTime);



        fprintf(stdout, "#Xferid=%ld,duration=%2lf\n",pairCnt, XferEndTime-XferStartTime);